# Generated by Django 5.0.6 on 2026-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('company_type', models.CharField(choices=[('municipality', 'Municipio'), ('private', 'Empresa privada'), ('ngo', 'ONG')], default='private', max_length=20, verbose_name='Tipo de empresa')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('billing_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de facturación')),
                ('billing_address', models.CharField(blank=True, max_length=300, verbose_name='Dirección de facturación')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
