# Generated by Django 5.0.6 on 2026-05-02 15:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color_hex', models.CharField(default='#00AA00', max_length=7, verbose_name='Color en mapa')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de residuo',
                'verbose_name_plural': 'Categorías de residuo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Ubicación GPS')),
                ('schedule', models.CharField(blank=True, max_length=300, verbose_name='Horario')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recycling_points/', verbose_name='Imagen')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'En mantención')], default='active', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_points', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Punto de reciclaje',
                'verbose_name_plural': 'Puntos de reciclaje',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WasteSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='points.wastecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría de residuo',
                'verbose_name_plural': 'Subcategorías de residuo',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Contenedor multireciclaje 1', max_length=100, verbose_name='Nombre')),
                ('capacity_liters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad (litros)')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'En mantención')], default='active', max_length=20, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='containers/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recycling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='points.recyclingpoint', verbose_name='Punto de reciclaje')),
                ('waste_subcategories', models.ManyToManyField(blank=True, related_name='containers', to='points.wastesubcategory', verbose_name='Tipos de residuo')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['recycling_point', 'name'],
            },
        ),
    ]
