# Generated by Django 5.0.6 on 2026-05-03 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Contenedor', 'verbose_name_plural': 'Contenedores'},
        ),
        migrations.RemoveField(
            model_name='container',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='image',
        ),
        migrations.RemoveField(
            model_name='container',
            name='name',
        ),
        migrations.RemoveField(
            model_name='container',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='waste_subcategories',
        ),
        migrations.RemoveField(
            model_name='wastecategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='wastesubcategory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='container',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='points.wastecategory', verbose_name='Categoría de residuo'),
        ),
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.CharField(choices=[('standard', 'Contenedor Estándar (Tacho)'), ('compost', 'Compostera / Vermicompostera'), ('specific', 'Contenedor Específico (Ej: Neumáticos)'), ('hazardous', 'Contenedor Autorizado (Aceites/Peligrosos)')], default='standard', max_length=20, verbose_name='Tipo de contenedor'),
        ),
        migrations.AddField(
            model_name='container',
            name='fill_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nivel de llenado actual (0% a 100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de llenado'),
        ),
        migrations.AddField(
            model_name='container',
            name='last_collection',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último retiro'),
        ),
        migrations.AddField(
            model_name='container',
            name='last_fill_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización de nivel'),
        ),
        migrations.AddField(
            model_name='container',
            name='required_state',
            field=models.CharField(blank=True, help_text='Ej: Limpio, seco y en botellas cerradas', max_length=200, verbose_name='Estado requerido del residuo'),
        ),
        migrations.AddField(
            model_name='wastesubcategory',
            name='icon_color',
            field=models.CharField(default='#00AA00', help_text='Hexadecimal, ej: #1565C0', max_length=7, verbose_name='Color del icono'),
        ),
        migrations.AddField(
            model_name='wastesubcategory',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Nombre del icono en Material Icons. Ej: 'recycling', 'water_drop'", max_length=100, verbose_name='Nombre de icono'),
        ),
        migrations.AddField(
            model_name='wastesubcategory',
            name='is_rep',
            field=models.BooleanField(default=False, verbose_name='Categoría REP'),
        ),
        migrations.AlterField(
            model_name='container',
            name='capacity_liters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad (Litros)'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'En mantención')], default='active', max_length=20, verbose_name='Estado del contenedor'),
        ),
    ]
