# Generated by Django 5.0.6 on 2026-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_container_options_remove_container_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubcategory',
            name='material_code',
            field=models.CharField(blank=True, help_text='Ej: 1 (PET), 2 (HDPE), ALU (Aluminio), GL (Vidrio), PAP (Papel)', max_length=10, verbose_name='Código de material'),
        ),
    ]
