# Generated by Django 5.0.6 on 2026-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_wastesubcategory_material_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='name',
            field=models.CharField(blank=True, help_text='Ej: Contenedor PET 1', max_length=100, verbose_name='Nombre'),
        ),
    ]
