# Generated by Django 5.0.6 on 2026-05-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_container_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='category',
        ),
        migrations.AddField(
            model_name='container',
            name='waste_subcategories',
            field=models.ManyToManyField(blank=True, to='points.wastesubcategory', verbose_name='Subcategorías de residuo'),
        ),
    ]
