# Generated by Django 5.0.6 on 2026-05-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_remove_container_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recyclingpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
