# Generated by Django 5.0.6 on 2026-05-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_alter_recyclingpoint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='last_fill_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización de nivel'),
        ),
    ]
